- name: Configuring agent in Zabbix server
  include_role:
    name: zabbix-server
    tasks_from: agent_config
  vars:
    zabbix_templates: "{{ mirror_cloud_zabbix_templates }}"
    zabbix_groups: "{{ mirror_cloud_zabbix_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined

- name: Zabbix check for cloud mirror age
  template:
    src: zabbix-check-cloud-status.sh.j2
    dest: /usr/lib/zabbix/zabbix-check-cloud-status.sh
    mode: 0750

- name: Zabbix cron jobs
  cron:
    name: Cloud Mirror content status
    job: /usr/lib/zabbix/zabbix-check-cloud-status.sh
    minute: "*/5"
